// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// The Prisma CLI (validate/generate/migrate) always connects via DIRECT_URL,
// not the pooled DATABASE_URL — Supabase's Supavisor pooler (port 6543,
// transaction mode) doesn't support the session-level features (advisory
// locks, prepared statements) that `prisma migrate` needs. The app's own
// runtime client (src/lib/db/client.ts) connects via DATABASE_URL (pooled)
// directly through its own pg.Pool + driver adapter — this config's url is
// CLI-only and never used at request time.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
